Updates to README.md
secure-device-onboard/all-in-one-demo pull request #28
Opened 2020-08-19 11:15 UTC by DukeDavis12

Updating the AIO README files to include the new OnPrem-RV
   integration information and to reflect the changes in this release.

Signed-off-by: Davis Benny <davis.benny@intel.com>

2020-08-19 15:18 UTC, trbehera requested changes

2020-08-19 15:18 UTC, trbehera commented on README.md
> +**docker-compose** instance. The purpose of this demo is to fast-track demonstration of Secure
docker-compose => docker

2020-08-19 15:18 UTC, trbehera commented on README.md
> +After successful build, the demo package is available at container/demo/aio.tar.gz.
container/demo/aio.tar.gz => demo/aio.tar.gz

2020-08-19 15:18 UTC, trbehera commented on container/overlay/README.md
> +Platform SDK Service and SDO Rendezvous Service from a single **docker-compose** instance. The
docker-compose => docker

2020-08-20 04:29 UTC, DukeDavis12 commented on container/overlay/README.md
> +Platform SDK Service and SDO Rendezvous Service from a single **docker-compose** instance. The
Updated.

2020-08-20 04:29 UTC, DukeDavis12 commented on README.md
> +After successful build, the demo package is available at container/demo/aio.tar.gz.
Updated.

2020-08-20 04:29 UTC, DukeDavis12 commented on README.md
> +**docker-compose** instance. The purpose of this demo is to fast-track demonstration of Secure
Updated.

2020-08-20 09:23 UTC, trbehera approved these changes

2020-08-20 09:41 UTC, KiranSukhavasi approved these changes

2020-08-20 10:48 UTC, trbehera approved these changes

2020-08-20 10:53 UTC, KiranSukhavasi approved these changes

2020-08-20 10:54 UTC, merged