Update AIO to support HTTPS
secure-device-onboard/all-in-one-demo pull request #64
Opened 2021-01-29 23:45 UTC by rftemple

README updated to show how to configure tomcat for TLS.
AIO Releay Servlet updated to use SSLContext.
AioDB updated to allow SCT to using http for RV Ifo.

Signed-off-by: Templeton, Randall <randall.f.templeton@intel.com>

2021-02-12 04:59 UTC, trbehera submitted a review, later dismissed

2021-02-12 12:05 UTC, trbehera submitted a review, later dismissed

2021-02-12 16:08 UTC, nsajadpx requested changes
in the README it would be good reference to add the below information regarding the docker usage.

Add below line to Dockerfile to add cert tot he java certs of the container.
     RUN keytool -import -trustcacerts -noprompt -keystore "/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts" -storepass changeit -alias tomcat -file <PATH_TO_CERT>

docker-compose.yaml
   extra_hosts:
          - "<Domain_Name_in_Cert>:127.0.0.1"

2021-02-12 16:08 UTC, nsajadpx commented on container/overlay/README.md
> +client.ssl.trust-store-type=JKS
JKS should be removed and changed to mention p12 formatted keystores are acceptable as well.

2021-02-22 17:26 UTC, trbehera approved these changes

2021-02-22 17:27 UTC, DukeDavis12 approved these changes

2021-02-22 19:58 UTC, nsajadpx approved these changes

2021-02-23 02:12 UTC, merged